spring.application.name=GerenciamentoLanchonete

spring.datasource.url=jdbc:postgresql://localhost:5432/lanchonete_db
spring.datasource.username=postgres
spring.datasource.password=141516

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
